<?php

//use Drupal\image\Entity\ImageStyle;

/**
 * Implements hook_preprocess_HOOK() for node templates.
 */
function purchase_form_preprocess_node( &$variables ) {
	//ddl($variables);
	if ($variables['node']->getType() == 'article') {
		$variables['contentTitle'] = $variables['node']->getTitle();
		$variables['contentBody'] = $variables['node']->get('body')->value;
		$image_file_id = $variables['node']->field_image[0]->target_id;
		$image_file = \Drupal\file\Entity\File::load($image_file_id);
		$uri = $image_file->uri->value;
		$variables['contentImage']=file_create_url($uri);
		//ddl($variables['contentImage']);
		}
	}	
	/*function purchase_form_preprocess_node( &$variables ) {
		if ($variables['node']->getType() == 'article') {
			if (($node = \Drupal::routeMatch()->getParameter('node')) && $node instanceof \Drupal\node\NodeInterface) {
			 	$variables['contentTitle'] = $variables['node']->getTitle();
				$variables['contentBody'] = $variables['node']->get('body')->value;
				$banneruri = $node->field_image->entity->getFileUri();
		    $style = \Drupal::entityTypeManager()
				  ->getStorage('image_style')
				  ->load('test');
		    $styleuri = $style->buildUri($banneruri);
		    if (!file_exists($styleuri)) {
		  		$style->createDerivative($banneruri, $styleuri);
					}
		    $variables['contentImage'] = file_url_transform_relative($style->buildUrl($banneruri));
				}
			}
		}	*/
	/*function my_user_token_values($type, $object = NULL, $options = array()) {
  if ($type == 'user') {
    $user = $object;
    $tokens['name']      = $user->name;
    $tokens['mail']      = $user->mail;
    return $tokens;
  }
}*/
		



